Update Dependencies
multiversx/mx-sdk-rs pull request #1003
Opened 2023-03-07 15:12 UTC by alyn509

- remove path from `dependencies`
- remove `dev-dependencies`

2023-03-07 18:31 UTC, andrei-marinica requested changes

2023-03-07 18:31 UTC, andrei-marinica commented on framework/meta/src/template.rs
> +    toml.dev_dependencies_mut().clear();
No, don't clear the dev-dependencies. They are needed for tests. Remove paths like for the regular dependencies.

2023-03-07 18:31 UTC, andrei-marinica commented on framework/meta/src/template.rs
> +    let deps_map = cargo_toml_contents.dependencies_mut();
You can iterate here through both dependencies and dev-dependencies.

Either chain the iterators, or 2 successive for loops.

2023-03-08 09:25 UTC, andrei-marinica approved these changes

2023-03-08 09:26 UTC, andrei-marinica commented on framework/meta/src/template.rs
> +pub fn update_dependencies(template: &str) {
In future PR: rename to template_crate_name.

We need to explicitly set the new project name too. But not now.

2023-03-08 09:53 UTC, ovstinga approved these changes

2023-03-08 09:57 UTC, merged