update default issue callback
multiversx/mx-sdk-rs pull request #1086
Opened 2023-05-09 08:51 UTC by alyn509

2023-05-09 10:32 UTC, sasurobert approved these changes

2023-05-09 14:32 UTC, andrei-marinica requested changes

2023-05-09 14:32 UTC, andrei-marinica commented on framework/base/src/storage/mappers/token_mapper_state.rs
> +#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode, Default)]
This encoding is not backwards compatible with the old TokenIdentifier stored in the token mapper.

To preserve backwards compatibility, it is possible to define an encoding where "" means TokenMapperState::NotSet, "pending" or something for Pending, and the verbatim token identifier for TokenIdentifier

2023-05-12 13:22 UTC, lcswillems commented
Why do we have a `clear` method? If we prevent the token to be issued twice, then having a `clear` method enables to escape this, no? I emit, I clear, I emit again. @sasurobert @andrei-marinica

2023-05-12 13:29 UTC, lcswillems approved these changes

2023-05-15 19:26 UTC, andrei-marinica approved these changes

2023-05-15 19:26 UTC, merged