Handle mxsc json unpack
multiversx/mx-sdk-rs pull request #1087
Opened 2023-05-09 08:56 UTC by CostinCarabas

2023-05-15 14:29 UTC, andrei-marinica requested changes

2023-05-15 14:29 UTC, andrei-marinica commented on sdk/scenario-format/tests/interpreter_test.rs
> +#[should_panic]
Unintuitively, should not panic.
When running using the debugger, we don't actually rely on these files. Their path is their sole identifier in this case, and only used as an identifier.
`file:` does not panic, neither should this. This fix should solve the failing rust tests in the CI.

2024-01-24 20:19 UTC, andrei-marinica approved these changes

2024-01-25 07:34 UTC, mihaicalinluca approved these changes

2024-01-25 09:13 UTC, BiancaIalangi approved these changes

2024-01-26 00:10 UTC, merged