Adder: Add upgrade SC mandos test
multiversx/mx-sdk-rs pull request #1161
Opened 2023-07-13 10:09 UTC by CostinCarabas

2023-07-13 10:28 UTC, andrei-marinica approved these changes

2023-07-13 10:44 UTC, andrei-marinica requested changes

2023-07-13 10:44 UTC, andrei-marinica commented on contracts/examples/adder/tests/adder_mandos_constructed_raw_upgrade_test.rs
> +                .argument("file:output/adder.wasm") // code
`BytesValue::interpret_from("file:output/adder.wasm", &ic)`
Otherwise it doesn't find the file.

2023-07-13 11:21 UTC, ovstinga submitted a review, later dismissed

2023-07-14 22:37 UTC, andrei-marinica submitted a review, later dismissed

2023-07-14 22:56 UTC, andrei-marinica approved these changes

2023-07-14 23:11 UTC, merged