Esdt attribute annotation for type export in abi
multiversx/mx-sdk-rs pull request #1253
Opened 2023-11-01 10:15 UTC by mihaicalinluca

2023-11-01 19:42 UTC, andrei-marinica requested changes

2023-11-01 19:42 UTC, andrei-marinica commented on contracts/feature-tests/abi-tester/abi_tester_expected_main.abi.json
> +    "esdtAttributes": []
The abi-tester is a great place to add a few tests of the new feature.

2023-11-01 19:42 UTC, andrei-marinica commented on framework/base/src/abi/contract_abi.rs
> +// #[derive(Clone, Debug)]
Delete commented code.

2023-11-01 19:42 UTC, andrei-marinica commented on framework/derive/src/parse/attributes/trait_prop_names.rs
> +pub(super) static PROP_ESDT_ATTRIBUTE: &str = "esdt_attribute";
Call a `cargo fmt` to sort out missing endlines at the end of files, and more.

2023-11-01 19:42 UTC, andrei-marinica commented on framework/derive/src/parse/attributes/util.rs
> +) -> (bool, Option<EsdtAttribute>) {
Looks like the bool is redundant, the Option is enough.

2023-11-01 19:42 UTC, andrei-marinica commented on framework/derive/src/parse/attributes/util.rs
> +pub(super) fn is_attribute_with_one_type_arg(
prefix `is_` is only appropriate when the result is just a bool

2023-11-01 19:42 UTC, andrei-marinica commented on framework/derive/src/parse/trait_argument_parse.rs
> +    if has_attr {
Again, the bool is redundant.
if let Some(esdt_attribute) = ...

2023-11-01 19:42 UTC, andrei-marinica commented on framework/meta/Cargo.toml
> +proc-macro2 = "1.0.66"
Only the derive crate knows about proc-macro2

2023-11-02 09:18 UTC, andrei-marinica requested changes

2023-11-02 09:18 UTC, andrei-marinica commented on contracts/feature-tests/abi-tester/src/abi_tester.rs
> +#[esdt_attribute("TICKER-3", u32)]
Two more things: 
- also add a ticker with a structure/enum. You already have `AbiManagedType` and `AbiEnum` in the contract 
- create a structure `OnlyShowsUpInEsdtAttributes`, doesn't need to contain any fields, the point of it is, we want to see if all structures in esdt attributes get added to the types section of the ABI correctly.

2023-11-02 09:18 UTC, andrei-marinica commented on framework/base/src/abi/contract_abi.rs
> +    pub fn get_type<T: TypeAbi>(arg_name: &'static str) -> EsdtAttributeAbi {
Rename to `new`

2023-11-02 09:18 UTC, andrei-marinica commented on framework/derive/src/generate/abi_gen.rs
> +            let (ticker, ty) = attr.into_tuple();
Looks a little over-engineered.
```
let ticker = esdt_attr.ticker;
let ty = &esdt_attr.ty;
```
No need for clone or into_tuple (at all).

2023-11-02 09:18 UTC, andrei-marinica commented on framework/derive/src/parse/attributes/util.rs
> +            let symbol: &'static str = Box::leak(Box::new(first_literal));
Memory leak!
No need for static str in derive. Use String! The static str is a trick we employ when generating code (might remove it there too...). There's no need to have it here.

2023-11-02 09:18 UTC, andrei-marinica commented on framework/derive/src/parse/attributes/util.rs
> +            let group = match syn::parse2::<Group>(tokens) {
Do we need to _parse_ the tokens?
I would expect an `if let Group(g) = tokens ... ` should be enough.

2023-11-03 09:33 UTC, andrei-marinica approved these changes

2023-11-03 09:50 UTC, alyn509 approved these changes

2023-11-03 09:51 UTC, merged

2023-11-06 07:47 UTC, razvanphp commented
So we still need to add the annotations for this to happen? `#[derive(TypeAbi)]` is not enough?