remove wasm renaming in template
multiversx/mx-sdk-rs pull request #1276
Opened 2023-11-20 16:00 UTC by alyn509

2023-12-13 09:04 UTC, BiancaIalangi approved these changes

2023-12-13 12:06 UTC, andrei-marinica requested changes

2023-12-13 12:06 UTC, andrei-marinica commented on framework/meta/src/cmd/standalone/template/template_adjuster.rs
> -        self.update_dependencies_wasm();
We need a check of the template tag (framework version). This can only be removed for v0.45.0 or newer.

2023-12-15 14:27 UTC, andrei-marinica requested changes

2023-12-15 14:27 UTC, andrei-marinica commented on framework/meta/src/cmd/standalone/template/copy_util.rs
> +    create_multiversx_json_file(target_root, args_tag);
This is overkill, te file exists in the old versions too, you just need to add its name to the whitelist.

2023-12-18 15:23 UTC, andrei-marinica submitted a review, later dismissed

2023-12-18 15:35 UTC, andrei-marinica approved these changes

2023-12-18 15:38 UTC, mihaicalinluca approved these changes

2023-12-18 15:45 UTC, merged