Bitflags library update
multiversx/mx-sdk-rs pull request #1290
Opened 2023-11-28 14:47 UTC by mihaicalinluca

2023-11-29 17:50 UTC, andrei-marinica requested changes

2023-12-07 14:25 UTC, andrei-marinica requested changes

2023-12-07 14:25 UTC, andrei-marinica commented on framework/wasm-adapter/src/api/blockchain_api_node.rs
> +        .unwrap()
Unwrap not allowed here, since it can panic.
We need to find a better solution.
Specifically in this case I think error can be ignored

2023-12-11 08:33 UTC, andrei-marinica commented on framework/wasm-adapter/src/api/blockchain_api_node.rs
> +        .unwrap()
in case of error, call
`error_hook::signal_error(message)`
on else

2023-12-11 14:18 UTC, andrei-marinica approved these changes

2023-12-11 15:01 UTC, BiancaIalangi approved these changes

2023-12-11 15:32 UTC, merged