Set mapper extra get from address features
multiversx/mx-sdk-rs pull request #1371
Opened 2023-12-27 13:50 UTC by mihaicalinluca

2023-12-27 15:27 UTC, psorinionut requested changes

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/queue_mapper.rs
> +    pub fn get_value_from_address(&self, address: &ManagedAddress<SA>, node_id: u32) -> T {
Let's keep the naming convention for public functions.
`get_value_at_address`

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/queue_mapper.rs
> +    pub fn get_value_from_address_option(
get_value_at_address_option

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/queue_mapper.rs
> +    pub fn front_from_address(&self, address: &ManagedAddress<SA>) -> Option<T> {
`front_at_address`

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/queue_mapper.rs
> +    pub fn back_from_address(&self, address: &ManagedAddress<SA>) -> Option<T> {
`back_at_address`

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/queue_mapper.rs
> +    pub fn iter_from_address(&self, address: &ManagedAddress<SA>) -> Iter<SA, T> {
`iter_at_address`

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/set_mapper.rs
> +        self.queue_mapper.is_empty()
I think here you should use `is_empty_at_address`

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/set_mapper.rs
>      pub fn len(&self) -> usize {
Add a `len_at_address` as well.

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/set_mapper.rs
> +    pub fn next_from_address(&self, address: &ManagedAddress<SA>, value: &T) -> Option<T> {
`next_at_address`

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/set_mapper.rs
> +    pub fn previous_from_address(&self, address: &ManagedAddress<SA>, value: &T) -> Option<T> {
`previous_at_address`

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/set_mapper.rs
> +    pub fn front_from_address(&self, address: &ManagedAddress<SA>) -> Option<T> {
`front_at_address`

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/set_mapper.rs
> +    pub fn back_from_address(&self, address: &ManagedAddress<SA>) -> Option<T> {
`back_at_address`

2023-12-27 15:27 UTC, psorinionut commented on framework/base/src/storage/mappers/set_mapper.rs
> +        self.queue_mapper.iter_from_node_id(node_id)
I think here we need a new addition in the queue_mapper.
`iter_from_node_id_at_address`

2024-01-23 13:46 UTC, andrei-marinica commented
Issue resolved in a different way in https://github.com/multiversx/mx-sdk-rs/pull/1384

2024-01-23 13:46 UTC, closed without merging