created generate mock address function
multiversx/mx-sdk-rs pull request #1388
Opened 2024-01-17 00:27 UTC by mihaicalinluca

2024-01-17 08:44 UTC, andrei-marinica submitted a review, later dismissed

2024-01-17 10:30 UTC, andrei-marinica requested changes

2024-01-17 10:30 UTC, andrei-marinica commented on vm/src/types/vm_address.rs
> +            "0x11111111111111110f0f111111116f776e65725f5f5f5f5f5f5f5f5f5f015f5f"
This is not correct. The first 10 bytes are 0.
Example generated address from VM:
`0x00000000000000000f0f11111111a94f5374fce5edbc8e2a8697c15331001234`

2024-02-02 10:37 UTC, andrei-marinica approved these changes

2024-02-02 10:59 UTC, CostinCarabas approved these changes

2024-02-02 11:15 UTC, merged