Proxies
multiversx/mx-sdk-rs pull request #1426
Opened 2024-02-12 12:40 UTC by BiancaIalangi

2024-02-14 11:16 UTC, andrei-marinica requested changes

2024-02-14 11:16 UTC, andrei-marinica commented on framework/meta/src/cli_args/cli_args_contract.rs
> +    GenerateProxies(GenerateOverwriteArg),
Don't reuse the same arg type for both snippets and proxies. Even if, by coincidence they currently contain the same fields, they are likely to eveolve in different directions in the future.

2024-02-14 11:16 UTC, andrei-marinica commented on framework/meta/src/cmd/contract/generate_proxy/proxy_crate_gen.rs
> +        File::create(&file).unwrap()
instead of .unwrap(), better `.expect("could not write proxy file")`

2024-02-16 08:34 UTC, andrei-marinica approved these changes

2024-02-16 08:39 UTC, mihaicalinluca approved these changes

2024-02-16 10:07 UTC, merged