upgrade constructor impl for unified syntax + fmt
multiversx/mx-sdk-rs pull request #1443
Opened 2024-02-22 03:25 UTC by mihaicalinluca

2024-02-23 10:09 UTC, BiancaIalangi approved these changes

2024-02-23 11:34 UTC, alyn509 approved these changes

2024-02-29 19:49 UTC, andrei-marinica requested changes
Code looks great, but we're still missing an ABI test in abi-tester

2024-02-29 19:49 UTC, andrei-marinica commented on framework/meta/src/cmd/contract/sc_config/contract_variant_validate.rs
> -        _ => Err("More than one contrctructor present. Exactly one method annotated with `#[init]` is required.".to_string()),
I think we can reorganize this to look better/simpler. How about
```
match (init_constructor.len(), upgrade_constructors.len()) {
    (0, 0) => nope
    (1, 0,) | (0, 1) | (1, 1) => Ok(()),
    (_, _) => nope
}
```

2024-03-01 16:45 UTC, andrei-marinica approved these changes

2024-03-01 16:46 UTC, merged