sc-meta proxy
multiversx/mx-sdk-rs pull request #1484
Opened 2024-03-19 09:29 UTC by BiancaIalangi

2024-03-19 09:39 UTC, mihaicalinluca submitted a review, later dismissed

2024-03-20 12:10 UTC, andrei-marinica requested changes

2024-03-20 12:10 UTC, andrei-marinica commented on framework/meta/src/cmd/contract/sc_config/sc_config_serde.rs
> +    #[serde(rename = "proxy-paths")]
no need for the Option
only `#[serde(default)]`

2024-03-20 12:10 UTC, andrei-marinica commented on contracts/examples/adder/sc-config.toml
> +[contracts.adder]
Let's try to make this part not mandatory.

To explain: if this file is missing, a default config is created. Let's make this also work when this fie exists, but contracts are not configured.

2024-03-20 20:00 UTC, andrei-marinica approved these changes

2024-03-20 20:06 UTC, mihaicalinluca approved these changes

2024-03-20 20:14 UTC, andrei-marinica commented
Re-created here: https://github.com/multiversx/mx-sdk-rs/pull/1489

2024-03-20 20:14 UTC, closed without merging