import FixedSupplyToken & Mergeable traits from mx-exchange-rs
multiversx/mx-sdk-rs pull request #1512
Opened 2024-03-27 08:42 UTC by alyn509

2024-03-27 08:42 UTC, dorin-iancu approved these changes

2024-03-27 09:38 UTC, andrei-marinica requested changes

2024-03-27 09:38 UTC, andrei-marinica commented on framework/base/src/types/managed/wrapped/traits/fixed_token_supply.rs
> +pub trait FixedSupplyToken<M: ManagedTypeApi> {
Looking great, but we should absolutely have some example in a contract and some tests.

2024-03-28 11:11 UTC, andrei-marinica approved these changes

2024-03-28 11:33 UTC, andrei-marinica submitted a review, later dismissed

2024-03-28 12:34 UTC, dorin-iancu commented on contracts/feature-tests/exchange-features/src/exchange_features.rs
> +            self.rule_of_three_non_zero_result(payment_amount, &BigUint::from(FULL_VALUE_SUPPLY));
Use `self.amount` instead of the const, otherwise, successive `into_part` will give the wrong value.

2024-03-28 12:34 UTC, dorin-iancu commented on contracts/feature-tests/exchange-features/src/exchange_features.rs
> +        other.amount > 0u64
Just return `true` here, no need to check the amount.

2024-03-28 12:35 UTC, dorin-iancu commented on contracts/feature-tests/exchange-features/src/exchange_features.rs
> +            amount: new_amount.clone(),
No need to `.clone`.

2024-03-28 13:04 UTC, dorin-iancu approved these changes

2024-03-28 17:28 UTC, andrei-marinica approved these changes

2024-04-01 10:02 UTC, merged