proxy pause sc migration to new proxy and unified syntax
multiversx/mx-sdk-rs pull request #1515
Opened 2024-03-27 17:40 UTC by mihaicalinluca

2024-03-28 15:43 UTC, andrei-marinica requested changes

2024-03-28 15:43 UTC, andrei-marinica commented on contracts/examples/proxy-pause/src/pause_sc_proxy.rs
> +// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.
You changed it by hand, delete the prelude. also the allows.

2024-03-28 15:43 UTC, andrei-marinica commented on contracts/examples/proxy-pause/src/pause_sc_proxy.rs
> +    pub fn init(
init is not part of this interface

2024-03-29 09:01 UTC, BiancaIalangi approved these changes

2024-03-29 09:29 UTC, merged