migration and new proxies for composability
multiversx/mx-sdk-rs pull request #1517
Opened 2024-03-28 09:37 UTC by mihaicalinluca

2024-03-28 11:41 UTC, andrei-marinica requested changes

2024-03-28 11:41 UTC, andrei-marinica commented on contracts/feature-tests/composability/promises-features/src/call_promises.rs
> +            .async_call()
No more need for `async_call()` it does nothing, it's just for backwards compatibility.

2024-03-28 11:41 UTC, andrei-marinica commented on contracts/feature-tests/composability/promises-features/src/call_sync_bt.rs
>              .execute_on_dest_context_with_back_transfers::<()>();
.returns(ReturnsBackTransfers)
.sync_call()

2024-03-29 10:00 UTC, BiancaIalangi approved these changes

2024-03-29 10:01 UTC, merged