Fix proxy
multiversx/mx-sdk-rs pull request #1518
Opened 2024-03-28 12:44 UTC by BiancaIalangi

2024-03-29 23:52 UTC, andrei-marinica requested changes

2024-03-29 23:52 UTC, andrei-marinica commented on framework/meta/src/cmd/contract/generate_proxy/proxy_generator.rs
> +    fn clean_paths(&self, proxy_crate: &str, rust_type: &str) -> String {
To see if this function works as expected, let's write some unit tests for it.

2024-04-01 17:50 UTC, andrei-marinica approved these changes

2024-04-02 10:48 UTC, mihaicalinluca approved these changes

2024-04-02 13:11 UTC, andrei-marinica approved these changes

2024-04-02 13:11 UTC, merged