replace contract_call function and ContractCall* structs with unified syntax correspondents
multiversx/mx-sdk-rs pull request #1530
Opened 2024-04-02 10:21 UTC by mihaicalinluca

2024-04-02 10:31 UTC, andrei-marinica requested changes

2024-04-02 10:31 UTC, andrei-marinica commented on contracts/examples/seed-nft-minter/src/distribution_module.rs
> +                .egld_or_single_esdt((token_id.clone(), token_nonce, payment_amount))
should work with references 
&token_id
&payment_amount

2024-04-02 10:31 UTC, andrei-marinica commented on contracts/feature-tests/composability/promises-features/src/call_promise_direct.rs
> +            .egld_or_multi_esdt(EgldOrMultiEsdtPayment::MultiEsdt(token_payments_vec))
.payment(token_payments_vec)

We only use EgldOrMultiEsdtPayment if the choice is at runtime

2024-04-02 10:31 UTC, andrei-marinica commented on contracts/feature-tests/composability/vault/src/vault.rs
> +                .egld_or_single_esdt(return_payment.clone())
.payment(&return_payment)

no clones should be needed anymore

2024-04-04 10:53 UTC, andrei-marinica approved these changes

2024-04-04 10:53 UTC, andrei-marinica commented on framework/base/src/types/interaction/tx.rs
> +    proxy_imports::{EgldOrEsdtTokenIdentifier, EgldOrEsdtTokenPaymentRefs, ManagedTypeApi},
`proxy_imports` is just for proxies, we shouldn't use it in the framework
it's annoying that the auto-completer defaults to it
we'll purge them from the framework, but it's ok, doesn't need to be in thie PR

2024-04-04 11:06 UTC, BiancaIalangi approved these changes

2024-04-04 11:20 UTC, merged