migration process to unified syntax for various contracts
multiversx/mx-sdk-rs pull request #1542
Opened 2024-04-08 14:22 UTC by mihaicalinluca

2024-04-08 17:21 UTC, andrei-marinica requested changes

2024-04-08 17:21 UTC, andrei-marinica commented on contracts/feature-tests/composability/esdt-contract-pair/first-contract/src/lib.rs
> +            .raw_call(ManagedBuffer::from(SECOND_CONTRACT_REJECT_ESDT_PAYMENT))
`.raw_call(SECOND_CONTRACT_REJECT_ESDT_PAYMENT)`
also works, more compact

2024-04-08 17:21 UTC, andrei-marinica commented on contracts/feature-tests/composability/scenarios/forw_raw_sync_echo.scen.json
> +}
would be nice to run `mx-scenario-go fmt .` here, to format the scenarios

2024-04-08 17:21 UTC, andrei-marinica commented on contracts/feature-tests/rust-testing-framework-tester/src/lib.rs
> +            .raw_call("call")
"add", not "call"

2024-04-08 17:21 UTC, andrei-marinica commented on contracts/feature-tests/rust-testing-framework-tester/src/lib.rs
> +            .arguments_raw(args)
If it's only 1 argument, better to replace with `.argument(value)`

2024-04-08 17:21 UTC, andrei-marinica commented on contracts/feature-tests/rust-testing-framework-tester/src/lib.rs
> +            .arguments_raw(args)
If it's only 1 argument, better to replace with .argument(value)

2024-04-08 17:21 UTC, andrei-marinica commented on framework/base/src/types/interaction/tx_exec/tx_exec_upgrade.rs
> +        &ManagedAddress<Api>,
Not like this. To generalize, make `To` generic, make it implement `TxToSpecified`, which has method `with_value_ref`

2024-04-08 17:21 UTC, andrei-marinica commented on framework/base/src/types/interaction/tx_exec/tx_exec_upgrade.rs
> +impl<Api, Payment, Gas, RH>
Same here. Generalize using `TxToSpecified`, not by duplicating the entire call.

2024-04-19 09:25 UTC, andrei-marinica approved these changes

2024-04-22 07:13 UTC, andrei-marinica approved these changes

2024-04-22 07:16 UTC, BiancaIalangi approved these changes

2024-04-22 07:18 UTC, merged