migration to unified syntax of blackbox tests for price aggregator
multiversx/mx-sdk-rs pull request #1552
Opened 2024-04-10 13:12 UTC by mihaicalinluca

2024-04-19 09:21 UTC, andrei-marinica requested changes

2024-04-19 09:21 UTC, andrei-marinica commented on contracts/core/price-aggregator/tests/price_aggregator_blackbox_test.rs
> +            .from(&from.to_address())
Should work directly as .from(from)

If it doesn't, then we need some more conversions.

2024-04-19 09:21 UTC, andrei-marinica commented on contracts/core/price-aggregator/tests/price_aggregator_blackbox_test.rs
> +        // let price_aggregator_contract = PriceAggregatorContract::new(PRICE_AGGREGATOR_ADDRESS_EXPR);
Clean up

2024-04-19 09:21 UTC, andrei-marinica commented on contracts/core/price-aggregator/tests/price_aggregator_blackbox_test.rs
> +        .from(&state.oracles[0].to_address())
Same, should work without .to_address()

2024-04-22 15:00 UTC, BiancaIalangi submitted a review, later dismissed

2024-04-22 16:16 UTC, andrei-marinica requested changes

2024-04-22 16:16 UTC, andrei-marinica commented on contracts/core/price-aggregator/tests/price_aggregator_proxy.rs
> +#[derive(TopEncode, TopDecode)]
I think the original version had more derives. Extract `#[type_abi]`

2024-04-22 16:16 UTC, andrei-marinica commented on contracts/core/price-aggregator/tests/price_aggregator_proxy.rs
> +pub struct NewRoundEvent<Api>
I think the original version had more derives. Extract `#[type_abi]`

2024-04-22 16:57 UTC, andrei-marinica approved these changes

2024-04-22 17:04 UTC, merged