From conversion for MultiValueN
multiversx/mx-sdk-rs pull request #1625
Opened 2024-05-13 09:36 UTC by BiancaIalangi

2024-05-13 10:06 UTC, mihaicalinluca approved these changes

2024-05-13 10:16 UTC, andrei-marinica requested changes

2024-05-13 10:16 UTC, andrei-marinica commented on contracts/feature-tests/scenario-tester/src/lib.rs
> +        let value1 = value.clone().add(1u32);
let value1 = value + 1u32;

2024-05-13 10:16 UTC, andrei-marinica commented on framework/base/src/abi/type_abi_impl_codec_multi.rs
>                  type Unmanaged = Self;
also implement `type  Unmanaged = $mval_struct<$($name::Unmanaged,)+*> `
and add a test

2024-05-14 06:52 UTC, mihaicalinluca approved these changes

2024-05-14 07:03 UTC, andrei-marinica approved these changes

2024-05-14 07:04 UTC, merged