sc-meta compare feature and github actions
multiversx/mx-sdk-rs pull request #1637
Opened 2024-05-20 16:40 UTC by mihaicalinluca

2024-05-20 17:33 UTC, alyn509 approved these changes

2024-05-21 09:01 UTC, andrei-marinica requested changes

2024-05-21 09:01 UTC, andrei-marinica commented on framework/meta/src/cmd/contract/generate_proxy/proxy_gen_main.rs
> +    proxy_generator.write_proxy_to_file();
You can keep it memory, and compare it there, I think it is a little easier.

The proxy generator needs to be able to output to a String

2024-05-23 12:09 UTC, BiancaIalangi approved these changes

2024-05-23 13:10 UTC, andrei-marinica approved these changes

2024-05-23 15:30 UTC, andrei-marinica commented
Re-created and merged from here: https://github.com/multiversx/mx-sdk-rs/pull/1643

2024-05-23 15:30 UTC, closed without merging