Generate custome proxy
multiversx/mx-sdk-rs pull request #1679
Opened 2024-06-10 10:43 UTC by BiancaIalangi

2024-06-10 14:43 UTC, andrei-marinica requested changes

2024-06-10 14:43 UTC, andrei-marinica commented on framework/meta-lib/src/contract/sc_config/contract_variant_builder.rs
> +            proxy_configs: HashMap::new(),
Proxies still form a Vec, there is no key

2024-06-10 14:43 UTC, andrei-marinica commented on framework/meta-lib/src/contract/sc_config/sc_config_model.rs
> +    pub proxy_configs: HashMap<ProxyConfigSerde, ContractVariant>,
It's still a Vec

2024-06-10 14:43 UTC, andrei-marinica commented on framework/meta-lib/src/contract/sc_config/contract_variant_builder.rs
> +) -> HashMap<ProxyConfigSerde, ContractVariant> {
Should be a Vec

2024-06-10 14:43 UTC, andrei-marinica commented on framework/meta-lib/src/contract/sc_config/contract_variant_builder.rs
> +) -> HashMap<ProxyConfigSerde, ContractVariant> {
The config should not be the key here, it should be part of the proxy config
You need to add the ContractVariant to the ProxyConfig

2024-06-12 11:04 UTC, andrei-marinica submitted a review, later dismissed

2024-06-12 12:25 UTC, mihaicalinluca approved these changes

2024-06-12 12:25 UTC, andrei-marinica approved these changes

2024-06-12 12:28 UTC, merged