upgrade fn gen in sc-meta snippets
multiversx/mx-sdk-rs pull request #1694
Opened 2024-07-02 13:22 UTC by mihaicalinluca

2024-07-02 13:24 UTC, andrei-marinica commented on framework/meta-lib/src/contract/generate_snippets/snippet_template_gen.rs
> +            upgrade_endpoint.name, upgrade_endpoint.rust_method_name
upgrade_endpoint.name is always "upgrade"
make it a constant somewhere (or use the one that already exists)

2024-07-02 13:26 UTC, andrei-marinica commented on framework/meta-lib/src/contract/generate_snippets/snippet_template_gen.rs
> +            upgrade_endpoint.name, upgrade_endpoint.rust_method_name
In fact, there shouldn't be a `name` field there, it's redundant, since only one value is allowed

2024-07-02 13:29 UTC, andrei-marinica requested changes

2024-07-02 13:29 UTC, andrei-marinica commented on framework/meta-lib/src/contract/generate_snippets/snippet_template_gen.rs
> +            upgrade_endpoint.name, upgrade_endpoint.rust_method_name
We need pre-processing protection for upgrade and init

2024-07-05 10:48 UTC, BiancaIalangi submitted a review, later dismissed

2024-07-05 11:19 UTC, andrei-marinica requested changes

2024-07-05 11:19 UTC, andrei-marinica commented on framework/derive/src/parse/attributes/payable_attr.rs
> +                    assert!(
Would be nice to extract these checks into a separate function

2024-07-05 11:19 UTC, andrei-marinica commented on framework/derive/src/parse/attributes/util.rs
> +                    let clean = literal
Would be nice to extract these checks into a separate function

2024-07-05 12:05 UTC, andrei-marinica approved these changes

2024-07-05 12:05 UTC, merged