Test for ManagedOption type name
multiversx/mx-sdk-rs pull request #1732
Opened 2024-08-19 10:03 UTC by BiancaIalangi

2024-08-19 11:42 UTC, mihaicalinluca approved these changes

2024-08-19 12:02 UTC, andrei-marinica requested changes

2024-08-19 12:02 UTC, andrei-marinica commented on contracts/feature-tests/rust-testing-framework-tester/src/lib.rs
> +    fn type_managed_option(
Let's move this to basic-features
There are some "echo" files with such endpoints

2024-08-19 13:56 UTC, mihaicalinluca submitted a review, later dismissed

2024-08-19 14:27 UTC, andrei-marinica approved these changes

2024-08-20 07:04 UTC, mihaicalinluca approved these changes

2024-08-20 07:05 UTC, mihaicalinluca approved these changes

2024-08-20 07:10 UTC, merged