added support for empty return data
multiversx/mx-sdk-rs pull request #1770
Opened 2024-09-10 16:32 UTC by mihaicalinluca

2024-09-11 08:44 UTC, BiancaIalangi approved these changes

2024-09-27 13:46 UTC, andrei-marinica approved these changes

2024-09-27 13:46 UTC, andrei-marinica requested changes

2024-09-27 13:46 UTC, andrei-marinica commented on sdk/core/src/data/vm.rs
> +    pub return_data: Option<Vec<String>>,
#[serde(Default)]

2024-10-01 11:02 UTC, BiancaIalangi submitted a review, later dismissed

2024-10-01 11:30 UTC, andrei-marinica commented
Re-targeted to master in https://github.com/multiversx/mx-sdk-rs/pull/1788

2024-10-01 11:30 UTC, closed without merging