View detect write op
multiversx/mx-sdk-rs pull request #1771
Opened 2024-09-12 15:21 UTC by BiancaIalangi

2024-09-17 17:54 UTC, andrei-marinica requested changes

2024-09-17 17:54 UTC, andrei-marinica commented on framework/meta-lib/src/tools/wasm_extractor.rs
> +const WRITE_OP: [&str; 1] = ["mBufferStorageStore"];
1. &[&str] = &[...]; - static slice is easier to write and cleaner
2. there are more write hooks: storageStore, int64storageStore, bigIntStorageStoreUnsigned, smallIntStorageStoreUnsigned, smallIntStorageStoreSigned
3. we should probably extend this to contract calls & transfers, they shouldn't be performed in a view, I think; event logs are also questionable

2024-09-17 17:54 UTC, andrei-marinica commented on framework/meta-lib/src/tools/wasm_extractor.rs
> +fn detect_write_operations_in_views(
It would be nice to also provide a unit test. It shouldn't be too difficult, you can embed the adder as a WAT.

2024-10-09 08:02 UTC, mihaicalinluca approved these changes

2024-10-09 08:16 UTC, merged