Interactor chain sim GitHub
multiversx/mx-sdk-rs pull request #1799
Opened 2024-10-02 19:41 UTC by BiancaIalangi

2024-10-10 09:57 UTC, mihaicalinluca submitted a review, later dismissed

2024-10-16 08:21 UTC, andrei-marinica requested changes

2024-10-16 08:21 UTC, andrei-marinica commented on contracts/examples/adder/interact/tests/basic_interact_cs_test.rs
> +    basic_interact.print_sum().await;
Let's have a method that returns the sum, so we can assert.

2024-10-16 08:21 UTC, andrei-marinica commented on contracts/examples/adder/interact/tests/basic_interact_cs_test.rs
> +    // basic_interact
Can we get this to work? So we don't leave commented code.

2024-10-16 16:34 UTC, andrei-marinica approved these changes

2024-10-16 16:35 UTC, mihaicalinluca approved these changes

2024-10-16 16:40 UTC, merged