migrations to unified for old tests
multiversx/mx-sdk-rs pull request #1851
Opened 2024-11-11 09:58 UTC by mihaicalinluca

2024-11-28 13:14 UTC, andrei-marinica requested changes

2024-11-28 13:14 UTC, andrei-marinica commented on contracts/feature-tests/scenario-tester/tests/st_blackbox_legacy_proxy_test.rs
> +const ADDER: TestSCAddress = TestSCAddress::new("adder");
This is a backwards compatibility test. Do not change!

2025-03-07 17:51 UTC, andrei-marinica approved these changes

2025-03-07 17:52 UTC, BiancaIalangi approved these changes

2025-03-07 18:19 UTC, merged