fix for scs with names containing -
multiversx/mx-sdk-rs pull request #1880
Opened 2024-11-27 13:20 UTC by mihaicalinluca

2024-11-27 13:22 UTC, BiancaIalangi approved these changes

2024-11-28 07:35 UTC, andrei-marinica approved these changes

2024-11-28 07:36 UTC, andrei-marinica requested changes

2024-11-28 07:36 UTC, andrei-marinica commented on framework/meta-lib/src/contract/generate_snippets/snippet_gen_main.rs
> +        let crate_name = &main_contract.contract_name.replace("-", "_");
Not the crate name needs to be changed, but the function names in code

2024-11-28 08:00 UTC, andrei-marinica approved these changes

2024-11-28 08:30 UTC, BiancaIalangi approved these changes

2024-11-28 10:10 UTC, andrei-marinica approved these changes

2024-11-28 10:20 UTC, merged