Add scenario for forwarder-queue
multiversx/mx-sdk-rs pull request #995
Opened 2023-03-01 19:13 UTC by CostinCarabas

Create multiple async calls via forwarder

2023-03-03 19:50 UTC, CostinCarabas commented
`run-scenarios "/home/costin/mvx/mx-sdk-rs/contracts/feature-tests/composability/forwarder-queue/scenarios/forw_raw_async_accept_egld.scen.json"`

2023-03-06 08:34 UTC, ovstinga approved these changes

2023-03-06 10:40 UTC, andrei-marinica requested changes

2023-03-06 10:40 UTC, andrei-marinica commented on contracts/feature-tests/composability/forwarder-queue/src/forwarder_queue.rs
> +                let contract_call = self
There is no need to work with the proxy, leave this else out and just use the calls above.

We will program it from the data we provide to it, there is no need to for this contract to know about the vault. We pass it the endpoint to call, so we can choose to make it call endpoints from the vault, from itself, or from other contracts.

2023-03-06 10:40 UTC, andrei-marinica commented on contracts/feature-tests/composability/forwarder-queue/src/forwarder_queue.rs
>      fn self_proxy(&self, to: ManagedAddress) -> crate::Proxy<Self::Api>;
No more need for the self proxy, we will allow it to call anything in a raw fashion.

2023-03-06 12:49 UTC, andrei-marinica approved these changes

2023-03-06 14:21 UTC, merged